#include <string>
#include "game.h"
#include "Framework\console.h"
#include <iostream>
#include <iomanip>
#include <sstream>
#include <fstream>
#include <stdlib.h>

void LevelOne();
void LevelTwo();
void LevelThree();
void LevelFour();
void LevelFive();
void LevelSix();
void LevelSeven();
void LevelEight();
void LevelNine();
void LevelTen();
void BonusRoom();
void renderSelectLevel();
void doorSwitchFive();